### ISSUE TITLE
TSNE depiction of embedding space

### ISSUE THREAD

**Issue by RImbriaco** [nhshin-mcl/QCN#4]
First, I'd like to thank you for researching this topic and making the code public. I am very excited to use your solution for IQA. I have a question regarding the visualization of representations. In fig. 8 of your paper, you show the t-SNE visualization of the embeddings and pivots across the three different updates. 

I have tried replicating these results using the KonIQ dataset and your provided weights but all my visualizations are nonsense. Could you please share how to obtain similar plots?

**Comment by JiaqiShi-Stu** [comment]
How?Please tell me, I have the same questions
